package com.fanuel.elevatordemo.dbmodels;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fanuel.elevatordemo.dbmodels.ElevatorLog;

import com.fanuel.elevatordemo.dbmodels.ElevatorLogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig elevatorLogDaoConfig;

    private final ElevatorLogDao elevatorLogDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        elevatorLogDaoConfig = daoConfigMap.get(ElevatorLogDao.class).clone();
        elevatorLogDaoConfig.initIdentityScope(type);

        elevatorLogDao = new ElevatorLogDao(elevatorLogDaoConfig, this);

        registerDao(ElevatorLog.class, elevatorLogDao);
    }
    
    public void clear() {
        elevatorLogDaoConfig.getIdentityScope().clear();
    }

    public ElevatorLogDao getElevatorLogDao() {
        return elevatorLogDao;
    }

}
