package com.fanuel.elevatordemo.dbmodels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ELEVATOR_LOG.
 */
public class ElevatorLog {

    private Long id;
    private String code;
    private java.util.Date date;
    private String status;
    private String remark;

    public ElevatorLog() {
    }

    public ElevatorLog(Long id) {
        this.id = id;
    }

    public ElevatorLog(Long id, String code, java.util.Date date, String status, String remark) {
        this.id = id;
        this.code = code;
        this.date = date;
        this.status = status;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
